# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
        ),
    ]
