# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 05:25
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wolf', '0003_remove_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=tagging.fields.TagField(blank=True, default=b'', help_text='Separate tags with spaces.', max_length=255),
        ),
    ]
